version: "3.9"

services:
  broker:
    build: .
    command: python src/broker/broker_central.py
    ports:
      - "5555:5555"
      - "5556:5556"

services:
  broker_video:
    build: .
    container_name: broker_video
    command: python src/broker/broker_video.py
    ports:
      - "5555:5555"
      - "5556:5556"

  client1:
    build: .
    command: python src/client/client_text.py user1 SALA_A
    depends_on:
      - broker

  client2:
    build: .
    command: python src/client/client_text.py user2 SALA_A
    depends_on:
      - broker